# Pronunciation dictionary for Kenyan names, locations, and brands
# Format: 'Name/Place/Brand': 'Phonetic or simplified pronunciation'

PRONUNCIATION_DICT = {
    # --- First Names ---
    'Abdi': 'AB-dee',
    'Abdullahi': 'ab-DOO-lah-hee',
    'Abel': 'AY-bel',
    'Abigail': 'AB-ih-gayl',
    'Abubakar': 'ah-boo-BAH-kar',
    'Adam': 'AD-am',
    'Adan': 'AH-dan',
    'Aden': 'AH-den',
    'Adhiambo': 'ah-thee-AM-bo',
    'Adoyo': 'ah-DOY-o',
    'Adrian': 'AY-dree-an',
    'Agnes': 'AG-nes',
    'Aisha': 'ah-EE-shah',
    'Akinyi': 'ah-KEE-nyee',
    'Albert': 'AL-bert',
    'Alex': 'AL-eks',
    'Alice': 'AL-is',
    'Ali': 'AH-lee',
    'Amina': 'ah-MEE-nah',
    'Amos': 'AY-mos',
    'Andrew': 'AN-droo',
    'Angela': 'AN-jeh-lah',
    'Ann': 'AN',
    'Anthony': 'AN-thoh-nee',
    'Antony': 'AN-toh-nee',
    'Arnold': 'AR-nold',
    'Arthur': 'AR-thur',
    'Asha': 'AH-shah',
    'Auma': 'OW-mah',
    'Austin': 'AW-stin',
    'Awino': 'ah-WEE-no',
    'Ayub': 'ah-YOOB',
    'Aziz': 'ah-ZEEZ',
    'Bakari': 'bah-KAH-ree',
    'Baraka': 'bah-RAH-kah',
    'Barasa': 'bah-RAH-sah',
    'Barbara': 'BAR-bah-rah',
    'Beatrice': 'BEE-ah-tris',
    'Benjamin': 'BEN-jah-min',
    'Benson': 'BEN-son',
    'Bernard': 'BER-nard',
    'Bernice': 'ber-NEES',
    'Betty': 'BET-ee',
    'Beverly': 'BEV-er-lee',
    'Boniface': 'BON-ih-fays',
    'Brenda': 'BREN-dah',
    'Brian': 'BRY-an',
    'Bruce': 'BROOS',
    'Calvin': 'KAL-vin',
    'Caroline': 'KAH-roh-line',
    'Catherine': 'KATH-er-in',
    'Cecilia': 'seh-SEEL-yah',
    'Charles': 'CHARLZ',
    'Chebet': 'cheh-BET',
    'Chebos': 'cheh-BOSS',
    'Chebii': 'cheh-BEE',
    'Chege': 'CHEH-geh',
    'Cherono': 'che-ROH-no',
    'Cheruiyot': 'che-ROO-yot',
    'Chepchirchir': 'chep-CHEER-cheer',
    'Chepchumba': 'chep-CHUM-bah',
    'Chepkemoi': 'chep-keh-MOY',
    'Chepkoech': 'chep-KO-ech',
    'Chepkorir': 'chep-ko-REER',
    'Cheplangat': 'chep-lan-GAT',
    'Chepngeno': 'chep-NGEH-no',
    'Chepkirui': 'chep-KEE-roo-ee',
    'Cheprono': 'chep-ROH-no',
    'Cheprotich': 'chep-roh-TEACH',
    'Chepruto': 'chep-ROO-to',
    'Cheptoo': 'chep-TOO',
    'Christine': 'KRIS-teen',
    'Christopher': 'KRIS-toh-fer',
    'Clara': 'KLAH-rah',
    'Claudia': 'KLAW-dee-ah',
    'Clement': 'KLEM-ent',
    'Clifford': 'KLIF-ord',
    'Constance': 'KON-stans',
    'Cornelius': 'kor-NEEL-yus',
    'Cynthia': 'SIN-thee-ah',
    'Damaris': 'DAH-mah-ris',
    'Daniel': 'DAN-yel',
    'Daphne': 'DAF-nee',
    'David': 'DAY-vid',
    'Deborah': 'DEB-oh-rah',
    'Dennis': 'DEN-is',
    'Diana': 'dye-AN-ah',
    'Dickson': 'DIK-son',
    'Doris': 'DOR-is',
    'Dorothy': 'DOR-oh-thee',
    'Douglas': 'DUG-las',
    'Duncan': 'DUN-kan',
    'Edith': 'EE-dith',
    'Edna': 'ED-nah',
    'Edward': 'ED-ward',
    'Edwin': 'ED-win',
    'Eileen': 'EYE-leen',
    'Elaine': 'eh-LAYN',
    'Eleanor': 'EL-eh-nor',
    'Elizabeth': 'eh-LIZ-ah-beth',
    'Elijah': 'eh-LIE-jah',
    'Ellen': 'EL-en',
    'Elsie': 'EL-see',
    'Emily': 'EM-ih-lee',
    'Emma': 'EM-ah',
    'Emmanuel': 'eh-MAN-yoo-el',
    'Eric': 'ER-ik',
    'Esther': 'ES-ter',
    'Eugene': 'YOO-jeen',
    'Eunice': 'YOO-nis',
    'Eva': 'EE-vah',
    'Evelyn': 'EV-eh-lin',
    'Everlyn': 'EV-er-lin',
    'Faith': 'FAYTH',
    'Farida': 'fah-REE-dah',
    'Fatuma': 'fah-TOO-mah',
    'Felix': 'FEE-liks',
    'Florence': 'FLOR-ens',
    'Francis': 'FRAN-sis',
    'Frank': 'FRANK',
    'Fred': 'FRED',
    'Fredrick': 'FRED-rik',
    'Gabriel': 'GAY-bree-el',
    'Geoffrey': 'JEF-ree',
    'George': 'JORJ',
    'Gerald': 'JER-ald',
    'Gertrude': 'GER-trood',
    'Gilbert': 'GIL-bert',
    'Gladys': 'GLAD-is',
    'Godfrey': 'GOD-free',
    'Grace': 'GRAYCE',
    'Graham': 'GRAY-am',
    'Gregory': 'GREG-oh-ree',
    'Halima': 'hah-LEE-mah',
    'Hannah': 'HAN-ah',
    'Harriet': 'HAR-ee-et',
    'Harry': 'HAR-ee',
    'Hassan': 'HAH-san',
    'Helen': 'HEL-en',
    'Henry': 'HEN-ree',
    'Herbert': 'HER-bert',
    'Hilda': 'HIL-dah',
    'Hillary': 'HIL-ah-ree',
    'Howard': 'HOW-ard',
    'Ibrahim': 'EE-brah-heem',
    'Irene': 'eye-REEN',
    'Isaac': 'EYE-zak',
    'Isaiah': 'eye-ZAY-ah',
    'Ishmael': 'ISH-may-el',
    'Ivan': 'EYE-van',
    'Jack': 'JAK',
    'Jackline': 'JACK-leen',
    'Jacob': 'JAY-kub',
    'James': 'JAYMZ',
    'Jane': 'JAYN',
    'Janet': 'JAN-et',
    'Janice': 'JAN-is',
    'Jared': 'JAH-red',
    'Jasper': 'JAS-per',
    'Jean': 'JEEN',
    'Jennifer': 'JEN-ih-fer',
    'Jeremiah': 'jer-ah-MY-ah',
    'Jeremy': 'JER-ah-mee',
    'Joan': 'JOHN',
    'Joel': 'JOH-el',
    'John': 'JON',
    'Jonathan': 'JON-ah-than',
    'Joshua': 'JOSH-oo-ah',
    'Joseph': 'JOH-sef',
    'Joyce': 'JOYCE',
    'Judy': 'JOO-dee',
    'Julia': 'JOO-lee-ah',
    'Juliet': 'JOO-lee-et',
    'Julius': 'JOO-lee-us',
    'Justus': 'JUS-tus',
    'Kagwiria': 'kah-GWEE-ree-ah',
    'Karen': 'KAH-ren',
    'Karanja': 'kah-RAN-jah',
    'Kassim': 'KAH-seem',
    'Katherine': 'KATH-er-in',
    'Kawira': 'kah-WEE-rah',
    'Kelvin': 'KEL-vin',
    'Kennedy': 'KEN-eh-dee',
    'Kenneth': 'KEN-eth',
    'Kevin': 'KEH-vin',
    'Khalid': 'KHAH-leed',
    'Kigen': 'KEE-gen',
    'Kimani': 'kee-MAH-nee',
    'Kipchirchir': 'keep-CHEER-cheer',
    'Kipchoge': 'keep-CHOH-geh',
    'Kipchumba': 'keep-CHUM-bah',
    'Kipkemoi': 'keep-keh-MOY',
    'Kipkemboi': 'keep-kem-BOY',
    'Kipkirui': 'keep-KEE-roo-ee',
    'Kipkoech': 'keep-KO-ech',
    'Kipkorir': 'keep-ko-REER',
    'Kiplagat': 'keep-lah-GAT',
    'Kiplangat': 'keep-lan-GAT',
    'Kipngeno': 'keep-NGEH-no',
    'Kipngetich': 'keep-ngeh-TEACH',
    'Kiprono': 'keep-ROH-no',
    'Kiprotich': 'keep-roh-TEACH',
    'Kipruto': 'keep-ROO-to',
    'Kiptoo': 'keep-TOO',
    'Kisilu': 'kee-SEE-loo',
    'Koech': 'ko-ECH',
    'Lilian': 'LEE-lee-an',
    'Lucy': 'LOO-see',
    'Lydia': 'LID-ee-ah',
    'Magdalene': 'MAG-dah-leen',
    'Maina': 'MY-nah',
    'Makena': 'mah-KAY-nah',
    'Margaret': 'MAR-gah-ret',
    'Mary': 'MAIR-ee',
    'Mercy': 'MER-see',
    'Mohamed': 'mo-HAH-med',
    'Moses': 'MOH-sez',
    'Muli': 'MOO-lee',
    'Mumo': 'MOO-mo',
    'Muriithi': 'moo-REE-thee',
    'Mutheu': 'moo-THEH-oo',
    'Nafula': 'nah-FOO-lah',
    'Naomi': 'nay-OH-mee',
    'Nyawira': 'nyah-WEE-rah',
    'Ochieng': 'oh-CHEE-eng',
    'Odhiambo': 'oh-thee-AM-bo',
    'Ogutu': 'oh-GOO-too',
    'Okoth': 'oh-KOTH',
    'Omollo': 'oh-MO-lo',
    'Onyango': 'oh-NYAN-go',
    'Opiyo': 'oh-PEE-yo',
    'Pamela': 'PAM-eh-lah',
    'Paul': 'PAWL',
    'Peter': 'PEE-ter',
    'Philip': 'FEE-leep',
    'Rashid': 'RAH-sheed',
    'Rebecca': 'reh-BEH-kah',
    'Rose': 'ROHZ',
    'Ruth': 'ROOTH',
    'Salim': 'SAH-leem',
    'Samuel': 'SAM-yoo-el',
    'Sarah': 'SAH-rah',
    'Sharon': 'SHAH-ron',
    'Silas': 'SYE-las',
    'Simon': 'SYE-mon',
    'Stephen': 'STEH-ven',
    'Susan': 'SOO-zan',
    'Tabitha': 'TAH-bee-thah',
    'Thomas': 'TOH-mas',
    'Victor': 'VIK-tor',
    'Wambua': 'wam-BOO-ah',
    'Waweru': 'wah-WAY-roo',
    'Yusuf': 'YOO-soof',

    # --- Kenyan Cities and Towns ---
    'Nairobi': 'ny-ROH-bee',
    'Mombasa': 'mom-BAH-sah',
    'Kisumu': 'kee-SOO-moo',
    'Nakuru': 'nah-KOO-roo',
    'Eldoret': 'el-dor-ET',
    'Thika': 'THEE-kah',
    'Kakamega': 'kah-kah-MAY-gah',
    'Meru': 'MEH-roo',
    'Nyeri': 'NYER-ee',
    'Machakos': 'mah-CHAH-kos',
    'Kisii': 'kee-SEE',
    'Kerugoya': 'keh-roo-GOY-ah',
    'Naivasha': 'ny-VAH-shah',
    'Kitale': 'kee-TAH-leh',
    'Malindi': 'mah-LIN-dee',
    'Lamu': 'LAH-moo',
    'Garissa': 'gah-REE-sah',
    'Wajir': 'WAH-jeer',
    'Mandera': 'man-DER-ah',
    'Marsabit': 'mar-SAH-bit',
    'Isiolo': 'ee-SEE-oh-lo',
    'Voi': 'VOY',
    'Bungoma': 'boon-GO-mah',
    'Busia': 'boo-SEE-ah',
    'Homa Bay': 'HOH-mah BAY',
    'Migori': 'mee-GOH-ree',
    'Siaya': 'see-AH-yah',
    'Kitui': 'kee-TWEE',
    'Makueni': 'mah-koo-EN-ee',
    'Taita Taveta': 'TAI-tah tah-VEH-tah',
    'Kwale': 'KWAH-leh',
    'Kilifi': 'kee-LEE-fee',
    'Tana River': 'TAH-nah RIV-er',
    'Samburu': 'sam-BOO-roo',
    'Turkana': 'tur-KAH-nah',
    'West Pokot': 'west poh-KOT',
    'Trans Nzoia': 'trans n-ZOY-ah',
    'Uasin Gishu': 'wah-SEEN GEE-shoo',
    'Nandi': 'NAN-dee',
    'Baringo': 'bah-RING-oh',
    'Laikipia': 'lie-KEEP-ee-ah',
    'Nyandarua': 'nyan-dah-ROO-ah',
    'Muranga': 'moo-RAHN-gah',
    'Kiambu': 'kee-AHM-boo',
    'Kirinyaga': 'kee-ree-NYAH-gah',
    'Embu': 'EM-boo',
    'Tharaka Nithi': 'thah-RAH-kah NEE-thee',
    'Vihiga': 'vee-HEE-gah',

    # --- Major Kenyan Brands ---
    'Safaricom': 'sah-FAH-ree-com',
    'M-Pesa': 'em-PAY-sah',
    'Equity Bank': 'EH-kwih-tee bank',
    'KCB': 'K C B',
    'Co-operative Bank': 'co-OP-er-ah-tiv bank',
    'Family Bank': 'FAM-ih-lee bank',
    'Absa': 'AB-sah',
    'NCBA': 'N C B A',
    'Stanbic': 'STAN-bik',
    'I&M Bank': 'I and M bank',
    'DTB': 'D T B',
    'Tusker': 'TUSS-ker',
    'Brookside': 'BROOK-side',
    'Kenya Airways': 'KEN-yah air-ways',
    'Nation Media': 'NAY-shun media',
    'Standard Group': 'STAN-dard group',
    'Royal Media': 'ROY-al media',
    'Citizen TV': 'SIT-ih-zen T V',
    'NTV': 'N T V',
    'KTN': 'K T N',
    'Radio Africa': 'RAY-dee-oh Africa',
    'Jumia': 'JOO-mee-ah',
    'Naivas': 'NIGH-vas',
    'Quickmart': 'KWIK-mart',
    'Chandarana': 'CHAN-dah-rah-nah',
    'Java House': 'JAH-vah house',
    'KenGen': 'KEN-gen',
    'Kenya Power': 'KEN-yah power',
    'Kenya Pipeline': 'KEN-yah pipe-line',
    'Kenya Ports Authority': 'KEN-yah ports authority',
    'Kenya Railways': 'KEN-yah rail-ways',
    'Kenya Re': 'KEN-yah ree',
    'NHIF': 'N H I F',
    'NSSF': 'N S S F',
    'Huduma': 'hoo-DOO-mah',
    'eCitizen': 'ee citizen',
    'Matatu': 'mah-TAH-too',
    'Boda Boda': 'BOH-dah BOH-dah',
    'Bidco': 'BID-co',
    'Brook Bond': 'BROOK bond',
    'Menengai': 'meh-NEN-guy',
    'Blue Band': 'BLUE band',
    'Tuskys': 'TUSS-kees',
    'Unga Group': 'OONG-ah group',
    'Kapa Oil': 'KAH-pah oil',
    'Mumias Sugar': 'moo-MEE-as sugar',
    'KETEPA': 'keh-TEH-pah',
    'Delmonte': 'DEL-mon-tay',
    'KCC': 'K C C',
    'KPLC': 'K P L C',
    'Kenpoly': 'KEN-poly',
    'Chapa Dimba': 'CHAH-pah DEEM-bah',
    'SportPesa': 'sport-PAY-sah',
    'Betika': 'beh-TEE-kah',
    'Airtel': 'AIR-tel',
    'Telkom': 'TEL-kom',
    'Faulu': 'FAH-oo-loo',
    'Jubilee Insurance': 'JOO-bih-lee insurance',

    # --- Kenyan Political Leaders ---
    'Uhuru Kenyatta': 'oo-HOO-roo ken-YAH-tah',
    'William Ruto': 'WIL-yam ROO-to',
    'Raila Odinga': 'RYE-lah oh-DING-ah',
    'Martha Karua': 'MAR-thah KAH-roo-ah',
    'George Wajackoyah': 'JORJ wah-jah-KOY-ah',
    'David Mwaure': 'DAY-vid mwah-OO-ray',
    'Mwai Kibaki': 'm-WYE kee-BAH-kee',
    'Daniel Moi': 'DAN-yel MOY',
    'Jomo Kenyatta': 'JOH-mo ken-YAH-tah',
    'Kalonzo Musyoka': 'kah-LON-zo moo-SYOH-kah',
    'Musalia Mudavadi': 'moo-SAH-lee-ah moo-dah-VAH-dee',
    'Moses Wetangula': 'MOH-sez weh-tan-GOO-lah',
    'Amos Wako': 'AH-mos WAH-ko',
    'Martha Wangari': 'MAR-thah wan-GAH-ree',
    'Charity Ngilu': 'CHA-rih-tee n-GEE-loo',
    'Peter Kenneth': 'PEE-ter KEN-eth',
    'Najib Balala': 'NAH-jeeb bah-LAH-lah',
    'Fred Matiangi': 'FRED mah-tee-AN-gee',
    'James Orengo': 'JAYMZ oh-REN-go',
    'Gladys Wanga': 'GLAD-is WAN-gah',
    'John Mbadi': 'JON m-BAH-dee',
    'Opiyo Wandayi': 'oh-PEE-yo wan-DYE',
    'Amos Kimunya': 'AH-mos kee-MOON-yah',
    'Mutula Kilonzo': 'moo-TOO-lah kee-LON-zo',
    'Kivutha Kibwana': 'kee-VOO-thah kee-BWAH-nah',
    'Hassan Joho': 'HAH-san JOH-ho',
    'Wycliffe Oparanya': 'WYE-klif oh-pah-RAHN-yah',
    'Anne Waiguru': 'AN weh-GOO-roo',
    'Kipchumba Murkomen': 'keep-CHUM-bah mur-KOH-men',
    'Susan Kihika': 'SOO-zan kee-HEE-kah',
    'Johnson Sakaja': 'JON-son sah-KAH-jah',
    'Mike Sonko': 'MIKE SON-ko',
    'Eugene Wamalwa': 'YOO-jeen wah-MAL-wah',
    'Rigathi Gachagua': 'ree-GAH-thee gah-CHA-goo-ah',
    'Kithure Kindiki': 'kee-THOO-ray kin-DEE-kee',
    'Aisha Jumwa': 'ah-EE-shah JOOM-wah',
    'Mithika Linturi': 'mee-THEE-kah lin-TOO-ree',
    'Peninah Malonza': 'peh-NEE-nah mah-LON-zah',
    'Alice Wahome': 'AL-is wah-HOH-may',
    'Moses Kuria': 'MOH-sez KOO-ree-ah',
    'Kipchumba Murkomen': 'keep-CHUM-bah mur-KOH-men',
    'Njuguna Ndungu': 'n-joo-GOO-nah n-DOON-goo',
    'Margaret Kobia': 'MAR-gah-ret KOH-bee-ah',
    'Simon Chelugui': 'SYE-mon cheh-LOO-gwee',
    'Betty Maina': 'BET-ee MY-nah',
    'Peter Munya': 'PEE-ter MOON-yah',
    'Ukur Yatani': 'OO-kur yah-TAH-nee',
    'James Macharia': 'JAYMZ mah-CHA-ree-ah',
    'Monica Juma': 'MON-ih-kah JOO-mah',
    'Raychelle Omamo': 'ray-CHEL oh-MAH-mo',
    'Fred Matiangi': 'FRED mah-tee-AN-gee',
    'George Magoha': 'JORJ mah-GOH-hah',
    'Mutahi Kagwe': 'moo-TAH-hee KAH-gweh',
    'Rashid Echesa': 'RAH-sheed eh-CHEH-sah',
    'Amina Mohamed': 'ah-MEE-nah mo-HAH-med',
    'Monica Juma': 'MON-ih-kah JOO-mah',
    'Raychelle Omamo': 'ray-CHEL oh-MAH-mo',
    'Fred Matiangi': 'FRED mah-tee-AN-gee',
    'George Magoha': 'JORJ mah-GOH-hah',
    'Mutahi Kagwe': 'moo-TAH-hee KAH-gweh',
    'Rashid Echesa': 'RAH-sheed eh-CHEH-sah',
    'Amina Mohamed': 'ah-MEE-nah mo-HAH-med'
}

# Helper function to clean and deduplicate the dictionary
def clean_pronunciation_dict():
    # Original dictionary with duplicates
    original_dict = {
        # ... existing code ...
    }
    
    # Create a new dictionary with unique entries
    cleaned_dict = {}
    seen_entries = set()
    
    # Process each entry
    for key, value in original_dict.items():
        # Normalize the key (remove extra spaces, convert to lowercase for comparison)
        normalized_key = key.strip().lower()
        
        # Only add if we haven't seen this entry before
        if normalized_key not in seen_entries:
            cleaned_dict[key] = value
            seen_entries.add(normalized_key)
    
    return cleaned_dict

# Create the cleaned dictionary
PRONUNCIATION_DICT = clean_pronunciation_dict()

# Remove the helper function after it's used
del clean_pronunciation_dict

# The dictionary is now clean and ready to use 